export const projects: IProjectScheme[] = [
  {
    name: "E-Commerce Platform",
    slug: "ecommerce-platform",
    thumbnail: "https://picsum.photos/400/430?random=1",
    liveLink: "https://example-ecommerce.com",
    githubLink: "https://github.com/example/ecommerce",
    details:
      "A full-featured e-commerce platform built with Vue and Node.js, featuring real-time inventory management, payment processing, and customer analytics.",
    tags: ["Vue.js", "Node.js", "PostgreSQL", "Stripe"],
    summary:
      "Full-featured e-commerce platform with real-time inventory management",
    status: "published",
  },
  {
    name: "Mobile App Dashboard",
    slug: "mobile-app-dashboard",
    thumbnail: "https://picsum.photos/400/430?random=2",
    liveLink: "https://example-dashboard.com",
    githubLink: "https://github.com/example/dashboard",
    details:
      "A comprehensive analytics dashboard for mobile app developers to track user engagement, crash reports, and performance metrics.",
    tags: ["React", "TypeScript", "Firebase", "Chart.js"],
    summary: "Analytics dashboard for tracking mobile app metrics",
    status: "published",
  },
  {
    name: "Content Management System",
    slug: "cms",
    thumbnail: "https://picsum.photos/400/500?random=3",
    liveLink: null,
    githubLink: "https://github.com/example/cms",
    details:
      "A headless CMS built with NuxtJS that allows content creators to manage and publish content across multiple platforms.",
    tags: ["Nuxt", "Vue", "Headless CMS"],
    summary: "Headless CMS for managing content across platforms",
    status: "draft",
  },
  {
    name: "AI Chat Bot",
    slug: "ai-chatbot",
    thumbnail: "https://picsum.photos/400/430?random=4",
    liveLink: "https://example-chatbot.com",
    githubLink: null,
    details:
      "An intelligent chatbot powered by GPT technology, designed for customer support and lead qualification.",
    tags: ["Python", "OpenAI", "FastAPI", "Vue"],
    summary: "AI-powered chatbot for customer support",
    status: "published",
  },
  {
    name: "Social Media Analytics",
    slug: "social-analytics",
    thumbnail: "https://picsum.photos/400/430?random=5",
    liveLink: "https://example-social-analytics.com",
    githubLink: "https://github.com/example/social-analytics",
    details:
      "Social media analytics tool that aggregates data from multiple platforms and provides actionable insights.",
    tags: ["Vue.js", "Express", "MongoDB"],
    summary: "Aggregated social media analytics platform",
    status: "published",
  },
  {
    name: "Project Management Tool",
    slug: "project-management",
    thumbnail: "https://picsum.photos/400/430?random=6",
    liveLink: null,
    githubLink: "https://github.com/example/pm-tool",
    details:
      "A Jira-like project management tool with real-time collaboration features and advanced reporting capabilities.",
    tags: ["Vue", "Node.js", "WebSockets"],
    summary: "Real-time project management and collaboration tool",
    status: "archieved",
  },
  {
    name: "Video Streaming Platform",
    slug: "video-streaming",
    thumbnail: "https://picsum.photos/400/500?random=7",
    liveLink: "https://example-video.com",
    githubLink: "https://github.com/example/video-streaming",
    details:
      "High-performance video streaming platform with adaptive bitrate and real-time transcoding capabilities.",
    tags: ["Vue", "Go", "FFmpeg", "AWS"],
    summary: "Scalable video streaming with adaptive bitrate",
    status: "published",
  },
  {
    name: "Design System",
    slug: "design-system",
    thumbnail: "https://picsum.photos/400/430?random=8",
    liveLink: "https://design-system-demo.com",
    githubLink: "https://github.com/example/design-system",
    details:
      "Comprehensive design system with reusable Vue components, design tokens, and documentation.",
    tags: ["Vue", "Storybook", "Design Tokens"],
    summary: "Comprehensive component library and design system",
    status: "published",
  },
  {
    name: "Real Estate Portal",
    slug: "real-estate",
    thumbnail: "https://picsum.photos/400/500?random=9",
    liveLink: "https://example-real-estate.com",
    githubLink: null,
    details:
      "Full-featured real estate listing platform with virtual tours, mortgage calculator, and agent management.",
    tags: ["Vue.js", "Node.js", "MongoDB", "Three.js"],
    summary: "Real estate marketplace with virtual tours and analytics",
    status: "published",
  },
  {
    name: "Learning Management System",
    slug: "lms",
    thumbnail: "https://picsum.photos/400/430?random=10",
    liveLink: "https://example-lms.com",
    githubLink: "https://github.com/example/lms",
    details:
      "Complete LMS with video lessons, quizzes, progress tracking, and certificate generation.",
    tags: ["Vue", "Python", "Django", "PostgreSQL"],
    summary: "Full-featured learning management system with video support",
    status: "published",
  },
  {
    name: "Fitness Tracking App",
    slug: "fitness-tracker",
    thumbnail: "https://picsum.photos/400/500?random=11",
    liveLink: "https://example-fitness.com",
    githubLink: "https://github.com/example/fitness",
    details:
      "Comprehensive fitness tracking app with workout plans, nutrition tracking, and social features.",
    tags: ["Vue", "Node.js", "Firebase", "Chart.js"],
    summary: "All-in-one fitness and wellness tracking platform",
    status: "published",
  },
  {
    name: "Invoice Generator",
    slug: "invoice-generator",
    thumbnail: "https://picsum.photos/400/430?random=12",
    liveLink: "https://example-invoices.com",
    githubLink: "https://github.com/example/invoices",
    details:
      "Professional invoice and billing management system with automated recurring billing and payment reminders.",
    tags: ["Vue", "Express", "PostgreSQL", "Stripe"],
    summary: "Professional invoice generation and billing platform",
    status: "published",
  },
];
